/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteImport } from './routes/test'
import { Route as CraftingRouteImport } from './routes/crafting'

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const CraftingRoute = CraftingRouteImport.update({
  id: '/crafting',
  path: '/crafting',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/crafting': typeof CraftingRoute
  '/test': typeof TestRoute
}
export interface FileRoutesByTo {
  '/crafting': typeof CraftingRoute
  '/test': typeof TestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/crafting': typeof CraftingRoute
  '/test': typeof TestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/crafting' | '/test'
  fileRoutesByTo: FileRoutesByTo
  to: '/crafting' | '/test'
  id: '__root__' | '/crafting' | '/test'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  CraftingRoute: typeof CraftingRoute
  TestRoute: typeof TestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crafting': {
      id: '/crafting'
      path: '/crafting'
      fullPath: '/crafting'
      preLoaderRoute: typeof CraftingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  CraftingRoute: CraftingRoute,
  TestRoute: TestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
