/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CraftingRouteImport } from './routes/crafting'

const CraftingRoute = CraftingRouteImport.update({
  id: '/crafting',
  path: '/crafting',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/crafting': typeof CraftingRoute
}
export interface FileRoutesByTo {
  '/crafting': typeof CraftingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/crafting': typeof CraftingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/crafting'
  fileRoutesByTo: FileRoutesByTo
  to: '/crafting'
  id: '__root__' | '/crafting'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  CraftingRoute: typeof CraftingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/crafting': {
      id: '/crafting'
      path: '/crafting'
      fullPath: '/crafting'
      preLoaderRoute: typeof CraftingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  CraftingRoute: CraftingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
